In [20]:
# importing libraries
import pandas as pd # data science essentials
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # enhanced data visualization
import statsmodels.formula.api as smf # regression modeling
from sklearn.model_selection import train_test_split # train/test split
from sklearn.linear_model import LinearRegression
import sklearn.linear_model
import statistics as stat # additional package that will be used for cleaning


# setting pandas print options
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

# specifying file name
file = './__datasets/birthweight_low.xlsx'


# reading the file into Python
# the next line removes the extra 'unnamed columns'
data = pd.read_excel (file, header=0) 
weight = pd.DataFrame(data, columns= ['mage',
                                           'meduc',
                                           'monpre',
                                           'npvis',
                                           'fage',
                                           'feduc',
                                           'omaps',
                                           'fmaps',
                                           'cigs',
                                           'drink',
                                           'male',
                                           'mwhte',
                                           'mblck',
                                           'moth',
                                           'fwhte',
                                           'fblck',
                                           'foth',
                                           'bwght'])
                       



weight.head(n=50)

    mage  meduc  monpre  npvis  fage  feduc  omaps  fmaps  cigs  drink  male  mwhte  mblck  moth  fwhte  fblck  foth  bwght
0     23   11.0       4   11.0    46   12.0      8      9    13      4     0      0      0     1      0      1     0   3600
1     23   16.0       3   10.0    50   12.0      3      8     1      1     1      0      1     0      0      1     0   3912
2     24   16.0       1   12.0    26   16.0      6      9    21      4     0      0      0     1      0      0     1   3090
3     25   14.0       3   12.0    33   12.0      9      9    12      7     1      0      1     0      0      1     0   3370
4     25   12.0       2    8.0    32   12.0      9      9     4      3     0      0      1     0      0      1     0   3827
5     26   12.0       1   10.0    24   12.0      8      9     6      8     1      0      0     1      0      0     1   2778
6     26   13.0       7   11.0    42    NaN      9      9     2      4     1      0      1     0      1      0     0   3170
7     26   11.0       1   12.0    44   12.0      9      9    10      4     1      0      1     0      0      1     0   3310
8     26   16.0       2   10.0    24   16.0      9      9    11      4     1      0      1     0      0      1     0   3730
9     26   12.0       1   12.0    32   12.0      9      9     6      0     1      0      1     0      0      1     0   3912
10    26   13.0       4    8.0    34   16.0      9      9     0      5     1      0      1     0      0      1     0   3925
11    26   16.0       2   12.0    42   16.0      9      9     5      1     1      0      0     1      1      0     0   4224
12    27   16.0       1    9.0    41   16.0      9      9     4      0     1      0      0     1      1      0     0   4040
13    28   12.0       2   10.0    37   10.0      9      9    11      8     0      1      0     0      1      0     0   2722
14    28   16.0       2   17.0    25   17.0      9      9     5      6     1      0      0     1      0      0     1   3320
15    28   12.0       2    6.0    37   12.0      8      9    13      4     0      0      1     0      0      1     0   3714
16    29   12.0       2   10.0    32   16.0      9      9    16     10     0      0      0     1      0      0     1   2780
17    29   17.0       2   30.0    49   17.0      9      9    17      4     1      0      1     0      0      1     0   3203
18    29   12.0       2    9.0    38   12.0      8      9     7      6     0      0      1     0      0      1     0   3255
19    29   14.0       2   19.0    41   17.0      9      9    14      5     1      0      1     0      0      1     0   3515
20    29   17.0       2   12.0    32   17.0      9     10    13      5     1      0      0     1      0      0     1   3742
21    30   14.0       2   13.0    42   12.0      8      9    16      8     1      0      1     0      0      1     0   3010
22    30   14.0       2    7.0    29   11.0      8      9    12      5     1      1      0     0      1      0     0   3449
23    30   16.0       2   11.0    41   17.0      9      9     5      8     0      1      0     0      1      0     0   3518
24    30   12.0       2   11.0    32   12.0      9     10     7      4     1      1      0     0      1      0     0   3756
25    30   13.0       2    8.0    35   11.0     10     10     8      6     0      1      0     0      1      0     0   3834
26    31   11.0       2   10.0    39    7.0      8      8     1      5     1      1      0     0      1      0     0   3254
27    31   12.0       2    6.0    36    NaN      7      9    16      2     0      0      1     0      0      0     1   3900
28    31   13.0       2    5.0    35   13.0      8     10     7      2     0      1      0     0      1      0     0   3905
29    31   17.0       2   12.0    27   17.0      9      9     6      2     0      0      1     0      1      0     0   3950
30    32   12.0       2   11.0    29   13.0      9      9    13     10     0      1      0     0      1      0     0   2359
31    32   12.0       2    9.0    36   14.0      9      9     9      8     1      0      1     0      0      1     0   3200
32    32   16.0       2   12.0    39   16.0      9     10    15      3     0      0      0     1      0      0     1   3300
33    32   10.0       2   12.0    30   12.0      9      9    11      4     1      0      0     1      1      0     0   3590
34    32   12.0       2   15.0    29   13.0      9     10    17      4     1      1      0     0      1      0     0   3629
35    32   12.0       2    NaN    38   14.0      9      9    13      0     1      0      1     0      0      1     0   4210
36    33   13.0       2   31.0    38    1.0      6      9    22      6     0      1      0     0      1      0     0   2544
37    33   14.0       2    9.0    36   12.0      9     10    13      8     0      1      0     0      1      0     0   3359
38    33   16.0       2    9.0    38   16.0      9      9    18      3     0      0      0     1      0      0     1   3655
39    33   13.0       2   15.0    40   12.0      8      9    12      1     1      1      0     0      1      0     0   3941
40    33   12.0       2   11.0    25   12.0      8      9     1      5     0      1      0     0      1      0     0   4050
41    34   16.0       2   15.0    31   12.0      9      9    11     10     1      0      1     0      1      0     0   2637
42    34    NaN       2    NaN    38   17.0      7      9    11      7     1      0      0     1      0      0     1   3610
43    34   16.0       2   12.0    29   16.0      8      8     1      8     0      1      0     0      1      0     0   3619
44    34   16.0       2   14.0    31   17.0      9      9    10      5     0      0      0     1      0      0     1   3685
45    34   12.0       2   12.0    39   12.0      9      9    10      6     0      0      1     0      0      1     0   3790
46    34   12.0       2   30.0    41   12.0      3      7     7      6     1      1      0     0      1      0     0   3792
47    34   16.0       2   13.0    28   16.0      8      9    11      5     1      0      1     0      0      1     0   3910
48    34   15.0       2   12.0    41   16.0      9      9     7      1     1      0      0     1      0      0     1   4090
49    35   11.0       2   10.0    28   11.0      9     10    16      7     0      1      0     0      1      0     0   2721

In [9]:
####Checking how many nulls
weight.isnull().sum(axis = 0)

mage      0
meduc     3
monpre    0
npvis     3
fage      0
feduc     7
omaps     0
fmaps     0
cigs      0
drink     0
male      0
mwhte     0
mblck     0
moth      0
fwhte     0
fblck     0
foth      0
bwght     0
dtype: int64

<b>NOTE:<b>
For the missing values in 'feduc' and 'meduc' it was assumed that they at least finished up until 12th grade.

While the npvis' NAs was filled with median.

In [21]:
######################
####Cleaning the data
######################


#imputing for feduc and meduc
fill = 12
weight['feduc'] = weight['feduc'].fillna(fill)
weight['meduc'] = weight['meduc'].fillna(fill)

##getting the median for npvis to fill up the NAs
temp_bw=weight.dropna()
med_npvis=stat.median(temp_bw['npvis'])
weight["npvis"]=weight["npvis"].fillna(med_npvis)

weight.isnull().sum(axis = 0)
weight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 352 entries, 0 to 351
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mage    352 non-null    int64
 1   meduc   352 non-null    float64
 2   monpre  352 non-null    int64
 3   npvis   352 non-null    float64
 4   fage    352 non-null    int64
 5   feduc   352 non-null    float64
 6   omaps   352 non-null    int64
 7   fmaps   352 non-null    int64
 8   cigs    352 non-null    int64
 9   drink   352 non-null    int64
 10  male    352 non-null    int64
 11  mwhte   352 non-null    int64
 12  mblck   352 non-null    int64
 13  moth    352 non-null    int64
 14  fwhte   352 non-null    int64
 15  fblck   352 non-null    int64
 16  foth    352 non-null    int64
 17  bwght   352 non-null    int64
dtypes: float64(3), int64(15)
memory usage: 49.6 KB

In [22]:
# log transforming bgwht and saving it to the dataset
weight['log_bwght'] = np.log(weight['bwght'])
# log transforming explanatory variables and saving it to the dataset
weight['log_meduc'] = np.log(weight['meduc']+0.001)
weight['log_drink'] = np.log(weight['drink']+0.001)
weight['log_mage'] = np.log(weight['mage']+ 0.001)
weight['log_monpre'] = np.log(weight['monpre'])
weight['log_npvis'] = np.log(weight['npvis']+0.001)
weight['log_fage'] = np.log(weight['fage'])
weight['log_feduc'] = np.log(weight['feduc']+0.001)
weight['log_omaps'] = np.log(weight['omaps'])
weight['log_fmaps'] = np.log(weight['fmaps'])
weight['log_cigs'] = np.log(weight['cigs']+0.001)

weight.head(n=10)

   mage  meduc  monpre  npvis  fage  feduc  omaps  fmaps  cigs  drink  male  mwhte  mblck  moth  fwhte  fblck  foth  bwght  log_bwght  log_meduc  log_drink  log_mage  log_monpre  log_npvis  log_fage  log_feduc  log_omaps  log_fmaps  log_cigs
0    23   11.0       4   11.0    46   12.0      8      9    13      4     0      0      0     1      0      1     0   3600   8.188689   2.397986   1.386544  3.135538    1.386294   2.397986  3.828641   2.484990   2.079442   2.197225  2.565026
1    23   16.0       3   10.0    50   12.0      3      8     1      1     1      0      1     0      0      1     0   3912   8.271804   2.772651   0.001000  3.135538    1.098612   2.302685  3.912023   2.484990   1.098612   2.079442  0.001000
2    24   16.0       1   12.0    26   16.0      6      9    21      4     0      0      0     1      0      0     1   3090   8.035926   2.772651   1.386544  3.178095    0.000000   2.484990  3.258097   2.772651   1.791759   2.197225  3.044570
3    25   14.0       3   12.0    33   12.0      9      9    12      7     1      0      1     0      0      1     0   3370   8.122668   2.639129   1.946053  3.218916    1.098612   2.484990  3.496508   2.484990   2.197225   2.197225  2.484990
4    25   12.0       2    8.0    32   12.0      9      9     4      3     0      0      1     0      0      1     0   3827   8.249836   2.484990   1.098946  3.218916    0.693147   2.079567  3.465736   2.484990   2.197225   2.197225  1.386544
5    26   12.0       1   10.0    24   12.0      8      9     6      8     1      0      0     1      0      0     1   2778   7.929487   2.484990   2.079567  3.258135    0.000000   2.302685  3.178054   2.484990   2.079442   2.197225  1.791926
6    26   13.0       7   11.0    42   12.0      9      9     2      4     1      0      1     0      1      0     0   3170   8.061487   2.565026   1.386544  3.258135    1.945910   2.397986  3.737670   2.484990   2.197225   2.197225  0.693647
7    26   11.0       1   12.0    44   12.0      9      9    10      4     1      0      1     0      0      1     0   3310   8.104703   2.397986   1.386544  3.258135    0.000000   2.484990  3.784190   2.484990   2.197225   2.197225  2.302685
8    26   16.0       2   10.0    24   16.0      9      9    11      4     1      0      1     0      0      1     0   3730   8.224164   2.772651   1.386544  3.258135    0.693147   2.302685  3.178054   2.772651   2.197225   2.197225  2.397986
9    26   12.0       1   12.0    32   12.0      9      9     6      0     1      0      1     0      0      1     0   3912   8.271804   2.484990  -6.907755  3.258135    0.000000   2.484990  3.465736   2.484990   2.197225   2.197225  1.791926

In [ ]:
weight_target

In [23]:
# preparing explanatory variable data
weight_data = weight.drop(['log_bwght','bwght','log_meduc','log_mage','log_monpre','npvis','log_fage','log_feduc',
                           'omaps','fmaps','cigs','drink'],axis=1)
                


# preparing response variable data
weight_target = weight.loc[ : , 'log_bwght']

#log_weight_target = weight.loc[ : , 'bgwght'] # For use later


# preparing training and testing sets (all letters are lowercase)
x_train, x_test, y_train, y_test = train_test_split(
            weight_data,
            weight_target,
            test_size = 0.25,
            random_state = 219)


# checking the shapes of the datasets
print(f"""
Training Data
-------------
X-side: {x_train.shape}
y-side: {y_train.shape[0]}


Testing Data
------------
X-side: {x_test.shape}
y-side: {y_test.shape[0]}
""")

Training Data
-------------
X-side: (264, 17)
y-side: 264


Testing Data
------------
X-side: (88, 17)
y-side: 88

In [24]:
# declaring set of x-variables
x_variables = ['meduc', 'mage', 'monpre',
               'log_npvis', 'fage', 'feduc',
               'log_omaps', 'log_fmaps', 'log_cigs',
               'log_drink', 'male', 'mwhte', 'mblck',
               'moth', 'fwhte', 'fblck', 'foth']


# looping to make x-variables suitable for statsmodels
for val in x_variables:
    print(f"{val} +")

meduc +
mage +
monpre +
log_npvis +
fage +
feduc +
log_omaps +
log_fmaps +
log_cigs +
log_drink +
male +
mwhte +
mblck +
moth +
fwhte +
fblck +
foth +

In [25]:
# merging X_train and y_train so that they can be used in statsmodels
weight_train = pd.concat([x_train, y_train], axis = 1)


# Step 1: INSTANTIATE a model object
lm_best = smf.ols(formula =  """ log_bwght~ 
meduc +
mage +
monpre +
log_npvis +
fage +
feduc +
log_omaps +
log_fmaps +
log_cigs +
log_drink +
male +
mwhte +
mblck +
moth +
fwhte +
fblck +
foth """,
data = weight_train)


# Step 2: FIT the data into the model object
results = lm_best.fit()


# Step 3: analyze the SUMMARY output
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              log_bwght   R-squared:                       0.546
Model:                            OLS   Adj. R-squared:                  0.519
Method:                 Least Squares   F-statistic:                     19.90
Date:                Sun, 13 Mar 2022   Prob (F-statistic):           1.52e-34
Time:                        20:22:05   Log-Likelihood:                 61.801
No. Observations:                 264   AIC:                            -91.60
Df Residuals:                     248   BIC:                            -34.39
Df Model:                          15
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.7754      0.221     17.110      0.000       3.341       4.210
meduc         -0.0035      0.007     -0.532      0.595      -0.017       0.010
mage          -0.0026      0.002     -1.496      0.136      -0.006       0.001
monpre         0.0627      0.053      1.174      0.241      -0.042       0.168
log_npvis      0.1016      0.030      3.365      0.001       0.042       0.161
fage          -0.0070      0.002     -4.363      0.000      -0.010      -0.004
feduc          0.0052      0.006      0.866      0.387      -0.007       0.017
log_omaps      0.0690      0.036      1.893      0.060      -0.003       0.141
log_fmaps      0.7266      0.149      4.861      0.000       0.432       1.021
log_cigs      -0.0002      0.005     -0.043      0.966      -0.011       0.010
log_drink     -0.0066      0.006     -1.185      0.237      -0.017       0.004
male           0.0313      0.027      1.180      0.239      -0.021       0.084
mwhte          1.2191      0.085     14.424      0.000       1.053       1.386
mblck          1.2635      0.084     15.100      0.000       1.099       1.428
moth           1.2929      0.087     14.884      0.000       1.122       1.464
fwhte          1.2582      0.080     15.638      0.000       1.100       1.417
fblck          1.2941      0.092     14.014      0.000       1.112       1.476
foth           1.2231      0.082     14.833      0.000       1.061       1.385
==============================================================================
Omnibus:                        9.916   Durbin-Watson:                   1.986
Prob(Omnibus):                  0.007   Jarque-Bera (JB):               13.211
Skew:                          -0.288   Prob(JB):                      0.00135
Kurtosis:                       3.932   Cond. No.                     7.64e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.67e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

<b>DEVELOPING LINEAR REGRESSION ON SCIKIT-LEARN<b>

In [26]:
# applying model in scikit-learn

# Preparing a DataFrame based the the analysis above
ols_weight_data = weight.loc[ : , x_variables]


# Preparing the target variable
weight_target = weight.loc[ : , 'log_bwght']


###############################################
## setting up more than one train-test split ##
###############################################
# FULL X-dataset (normal Y)
x_train_FULL, x_test_FULL, y_train_FULL, y_test_FULL = train_test_split(
            weight_data,     # x-variables
            weight_target,   # y-variable
            test_size = 0.25,
            random_state = 219)


# OLS p-value x-dataset (normal Y)
x_train_OLS, x_test_OLS, y_train_OLS, y_test_OLS = train_test_split(
            ols_weight_data,         # x-variables
            weight_target,   # y-variable
            test_size = 0.25,
            random_state = 219)

In [27]:
lr = LinearRegression()


# FITTING to the training data
lr_fit = lr.fit(x_train_OLS, y_train_OLS)


# PREDICTING on new data
lr_pred = lr_fit.predict(x_test_OLS)


# SCORING the results
print('OLS Training Score :', lr.score(x_train_OLS, y_train_OLS).round(4))
print('OLS Testing Score  :', lr.score(x_test_OLS, y_test_OLS).round(4))


# saving scoring data for future use
lr_train_score = lr.score(x_train_OLS, y_train_OLS).round(4) # using R-square
lr_test_score  = lr.score(x_test_OLS, y_test_OLS).round(4)   # using R-square


# displaying and saving the gap between training and testing
print('OLS Train-Test Gap :', abs(lr_train_score - lr_test_score).round(4))
lr_test_gap = abs(lr_train_score - lr_test_score).round(4)

OLS Training Score : 0.5462
OLS Testing Score  : 0.533
OLS Train-Test Gap : 0.0132

In [28]:
# zipping each feature name to its coefficient
lr_model_values = zip(weight_data[x_variables].columns,
                      lr_fit.coef_.round(decimals = 2))


# setting up a placeholder list to store model features
lr_model_lst = [('intercept', lr_fit.intercept_.round(decimals = 2))]


# printing out each feature-coefficient pair one by one
for val in lr_model_values:
    lr_model_lst.append(val)
    

# checking the results
for pair in lr_model_lst:
    print(pair)

('intercept', 6.29)
('meduc', -0.0)
('mage', -0.0)
('monpre', 0.06)
('log_npvis', 0.1)
('fage', -0.01)
('feduc', 0.01)
('log_omaps', 0.07)
('log_fmaps', 0.73)
('log_cigs', -0.0)
('log_drink', -0.01)
('male', 0.03)
('mwhte', -0.04)
('mblck', 0.01)
('moth', 0.03)
('fwhte', -0.0)
('fblck', 0.04)
('foth', -0.04)

<b>DEVELOPING ARD MODEL<b>

In [29]:
# INSTANTIATING a model object
ard_model = sklearn.linear_model.ARDRegression(normalize  = False)


# FITTING the training data
ard_fit = ard_model.fit(x_train_FULL, y_train_FULL)


# PREDICTING on new data
ard_pred = ard_fit.predict(x_test_FULL)


print('Training Score:', ard_model.score(x_train_FULL, y_train_FULL).round(4))
print('Testing Score :',  ard_model.score(x_test_FULL, y_test_FULL).round(4))


# saving scoring data for future use
ard_train_score = ard_model.score(x_train_FULL, y_train_FULL).round(4)
ard_test_score  = ard_model.score(x_test_FULL, y_test_FULL).round(4)


# displaying and saving the gap between training and testing
print('ARD Train-Test Gap :', abs(ard_train_score - ard_test_score).round(4))
ard_test_gap = abs(ard_train_score - ard_test_score).round(4)

Training Score: 0.4202
Testing Score : 0.417
ARD Train-Test Gap : 0.0032

In [30]:
# zipping each feature name to its coefficient
ard_model_values = zip(weight_data.columns, ard_fit.coef_.round(decimals = 4))


# setting up a placeholder list to store model features
ard_model_lst = [('intercept', ard_fit.intercept_.round(decimals = 2))]


# printing out each feature-coefficient pair one by one
for val in ard_model_values:
    ard_model_lst.append(val)
    

# checking the results
for pair in ard_model_lst:
    print(pair)

('intercept', 5.05)
('mage', 0.0)
('meduc', 0.0)
('monpre', 0.0029)
('fage', 0.0)
('feduc', 0.0)
('male', 0.0265)
('mwhte', -0.0031)
('mblck', 0.0)
('moth', 0.0)
('fwhte', 0.0)
('fblck', 0.0404)
('foth', 0.0)
('log_drink', 0.0)
('log_npvis', 0.1495)
('log_omaps', 0.1048)
('log_fmaps', 1.0927)
('log_cigs', 0.0)

In [ ]:
## This code may have to be run more than once ##

# dropping coefficients that are equal to zero

# printing out each feature-coefficient pair one by one
for feature, coefficient in ard_model_lst:
        
        if coefficient == 0:
            ard_model_lst.remove((feature, coefficient))

            
# checking the results
for pair in ard_model_lst:
    print(pair)

<b>DEVELOPING LASSO MODEL<b>

In [32]:
# INSTANTIATING a model object
lasso_model = sklearn.linear_model.Lasso(alpha     = 1.0,  # default shrinkage
                                         normalize = True) # default magitude


# FITTING to the training data
lasso_fit = lasso_model.fit(x_train_FULL, y_train_FULL)


# PREDICTING on new data
lasso_pred = lasso_fit.predict(x_test_FULL)


# SCORING the results
print('Lasso Training Score :', lasso_model.score(x_train_FULL, y_train_FULL).round(4))
print('Lasso Testing Score  :', lasso_model.score(x_test_FULL, y_test_FULL).round(4))


## the following code has been provided for you ##

# saving scoring data for future use
lasso_train_score = lasso_model.score(x_train_FULL, y_train_FULL).round(4) # using R-square
lasso_test_score  = lasso_model.score(x_test_FULL, y_test_FULL).round(4)   # using R-square


# displaying and saving the gap between training and testing
print('Lasso Train-Test Gap :', abs(lasso_train_score - lasso_test_score).round(4))
lasso_test_gap = abs(lasso_train_score - lasso_test_score).round(4)

Lasso Training Score : 0.0
Lasso Testing Score  : -0.0002
Lasso Train-Test Gap : 0.0002

In [ ]:
# zipping each feature name to its coefficient
lasso_model_values = zip(weight_data.columns, lasso_fit.coef_.round(decimals = 2))


# setting up a placeholder list to store model features
lasso_model_lst = [('intercept', lasso_fit.intercept_.round(decimals = 2))]


# printing out each feature-coefficient pair one by one
for val in lasso_model_values:
    lasso_model_lst.append(val)
    

# checking the results
for pair in lasso_model_lst:
    print(pair)

In [ ]:
# dropping coefficients that are equal to zero

# printing out each feature-coefficient pair one by one
for feature, coefficient in lasso_model_lst:
        
        if coefficient == 0:
            lasso_model_lst.remove((feature, coefficient))

            
# checking the results
for pair in lasso_model_lst:
    print(pair)

In [35]:
##COMPARING RESULTS OF THE 3 Models

print(f"""
Model      Train Score      Test Score      Test Gap          
-----      -----------      ----------      ----------
OLS        {lr_train_score}           {lr_test_score}           {lr_test_gap}
Lasso      {lasso_train_score}           {lasso_test_score}           {lasso_test_gap}
ARD        {ard_train_score}           {ard_test_score}           {ard_test_gap}
""")





if max(lr_test_score, lasso_test_score, ard_test_score) == lasso_test_score and lasso_test_gap < 0.05:
    print('Lasso')
elif  max(lr_test_score, ard_test_score) == lr_test_score and lr_test_gap < 0.05:
    print('OLS')
else: print ('ARD Model')

Model      Train Score      Test Score      Test Gap
-----      -----------      ----------      ----------
OLS        0.5462           0.533           0.0132
Lasso      0.0           -0.0002           0.0002
ARD        0.4202           0.417           0.0032

OLS

<b>Developing Histo Plot to  Find Skewed variables<b>

In [ ]:
##########################################
#######Developing Histo Plot to  Find Skewed variables
#####################################

# developing a histogram for birthweight
sns.histplot(data   = weight,
             x      = 'meduc',
             kde    = True)


# title and axis labels
plt.title(label   = "Original Distribution")
plt.xlabel(xlabel = "meduc") # avoiding using dataset labels
plt.ylabel(ylabel = "Count")

# displaying the histogram
plt.show()






# developing a histogram for mother educ
sns.histplot(data   = weight,
             x      = 'cigs',
             kde    = True)


# title and axis labels
plt.title(label   = "Original Distribution")
plt.xlabel(xlabel = "cigs") # avoiding using dataset labels
plt.ylabel(ylabel = "Count")

# displaying the histogram
plt.show()




# developing a histogram for drink
sns.histplot(data   = weight,
             x      = 'feduc',
             kde    = True)


# title and axis labels
plt.title(label   = "Original Distribution")
plt.xlabel(xlabel = "feduc") # avoiding using dataset labels
plt.ylabel(ylabel = "Count")

# displaying the histogram
plt.show()

# developing a histogram for npvis
sns.histplot(data   = weight,
             x      = 'fmap',
             kde    = True)
# title and axis labels
plt.title(label   = "Original Distribution ")
plt.xlabel(xlabel = "fmaps") # avoiding using dataset labels
plt.ylabel(ylabel = "Count")
# displaying the histogram
plt.show()